// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwRg6BLV8XeYS28APFYxi-TL8CT_FWM4M',
    appId: '1:517620440641:android:d78e444a292d2001f5f0c0',
    messagingSenderId: '517620440641',
    projectId: 'assigment7-c359f',
    databaseURL: 'https://assigment7-c359f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'assigment7-c359f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2YcpiBd1tRnA2-jdVo9pLlLpF6PKdcBw',
    appId: '1:517620440641:ios:e272e56440477a45f5f0c0',
    messagingSenderId: '517620440641',
    projectId: 'assigment7-c359f',
    databaseURL: 'https://assigment7-c359f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'assigment7-c359f.firebasestorage.app',
    androidClientId: '517620440641-of1on325a03fp30stgo87sk7j2a27ja6.apps.googleusercontent.com',
    iosClientId: '517620440641-c0qrslng0saejch93q09igk8jgvdg7tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.cross',
  );

}